title: "Geekify" 
email: "geekify@free.fr"
description: "Yet another maker's blog"
repository: "mchacher/mchacher.github.io"
url: "https://mchacher.github.io"
#baseurl: "https://mchacher.github.io"


include:
  - _pages
  - assets
  - index.html

exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "geekify"
logo: "/assets/images/geekify_logo.png"

  
# settings for author profile
author:
  name   : "Marc Chachereau"
  avatar : "/assets/images/headshot.jpg"
  bio    : "I enjoy writing about things I'm interested in - mostly electronics, software engineering and 3D printing.  
           All these domains combined, makes me a maker, enjoying home automation or any other areas where I can put my creativity to work."
  location: "Grenoble area, France"
  github : mchacher
  linkedin: marc-chachereau-067a9a4


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      title: " "
      title_separator: "|"
      author_profile: true

  - scope:
      path: ""
      type: posts
    values:
      layout: single
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true